#!/usr/bin/python
# encoding=utf-8

import sys
from sshconlib import *

#######################################################################################################
# main entry
#######################################################################################################

if len(sys.argv) > 1 :
	server_desc = sys.argv[1]

#######################################################################################################
# 1. 如果命令行未输入服务器信息，则先解密scfile，列出所有服务器配置信息

scfile = '.servers'

# 提示输入密码
#passwd_input = getpass.getpass('Please input password: ')
passwd_input = 'abc123'

# 进行解密
sc_list_all = decode_scfile_for_list(scfile, passwd_input)
if not sc_list_all :
	print 'Failed to decode the server configuration file !'
	exit(-1)


# 显示服务器列表
display_sc_list(sc_list_all)

#######################################################################################################
# 提示输入服务器配置信息

value_input = ''
sc_list_select1 = sc_list_all
sc_list_select2 = []
tries = 0

print '请输入序号、服务器名称或者IP地址(如果输入纯数字，则当成序号;'
print '如果包含数字和点号"."，则当成IP地址; 如果包含字符，则当成服务器名称),'
print '输入q、quit、exit退出。'

while not value_input and tries < 3:
	
	#sc_seq_no = []
	sc_server_name = []
	sc_ip = []
	for sc in sc_list_select1 :
		sc_var = sc.split(SEPARATOR)
		if len(sc_var) >= 3 :
			#sc_seq_no.append(sc_var[0])
			sc_server_name.append(sc_var[0])
			sc_ip.append(sc_var[1])
		
	value_input = raw_input('请输入: ')

	if not value_input :
		print '您未输入。请输入序号、服务器名称或者IP地址。'
	elif 'Q' == value_input.upper() or 'QUIT' == value_input.upper() or 'EXIT' == value_input.upper() :
		exit(0)

	# 判断用户输入是序号、服务器名称还是IP地址
	result = check_sc_select(value_input)
	
	if len(value_input) == 1 and result <> 1 :
		if result == 2 :		# 纯数字
			print '您输入的IP地址太短，请重新输入。'
		if result == 3 :
			print '您输入的服务器名称太短，请重新输入。'

		value_input = ''
		tries += 1
		continue


	# 用户输入服务器配置后，如果找到多项配置，则继续提示用户选择
	# 如果是唯一项，则执行ssh远程连接

	if result == 1 :			# 用户输入的是纯数字，序号
		for i in range(0, len(sc_list_select1)) :
			if i + 1 == int(value_input) :
				sc_list_select2.append(sc_list_select1[i])
				
	elif result == 2 :		# 输入的是IP地址
		for i in range(0, len(sc_ip)) :
			if value_input in sc_ip[i] :
				sc_list_select2.append(sc_list_select1[i])
				
	elif result == 3 :
		for i in range(0, len(sc_server_name)) :
			if value_input in sc_server_name[i] :
				sc_list_select2.append(sc_list_select1[i])

	if len(sc_list_select2) == 0 :
		print '您输入的服务器配置信息未找到.'
	elif len(sc_list_select2) == 1 :
		print '\n连接到服务器: '
		display_sc_list(sc_list_select2)
		
		do_connect(sc_list_select2)
		
	else :		# 找到多条记录
		print '\n找到多条记录: '
		display_sc_list(sc_list_select2)
		sc_list_select1 = sc_list_select2
		sc_list_select2 = []
		value_input = ''
		tries -= 1
	
	tries += 1

if not value_input and tries >= 3 :
	print '您超过三次未输入任何字符，程序退出。'
	exit(-1)
