#!/usr/bin/python

import sys
print('=============Python import mode============')
#print('The command line arguments are: ')
#for i in sys.argv:
#	print (i)

print ('\nThe python path: \n')
print (sys.path)

